package com.example.capstone.domain.crosswalk.service.sync;

public enum FailureReason {
    MISSING_CODE,
    MISSING_COORDINATE,
    INVALID_COORDINATE,
    INVALID_GEOMETRY,
    COORDINATE_TRANSFORM_FAILED,
    COORDINATE_OUT_OF_RANGE,
    PARSE_DOUBLE_FAILED,
    PARSE_INTEGER_FAILED,
    PARSE_DATE_FAILED,
    UNSUPPORTED_DATE_FORMAT,
    INVALID_DATE_FORMAT,
    EMPTY_ITEMS,
    INVALID_RESPONSE,
    OPEN_API_ERROR
}